import createActionType from '../../utils/createActionTypes';

export default createActionType([
  'APPLICATIONLIST_REQUEST',
  'APPLICATIONLIST_RESPONSE',
  'APPLICATIONDETAIL_RESPONSE',
  'APPLICATIONLIST_ERROR',
  'APPLICATIONLIST_MODAL_DELETE_OPEN',
  'APPLICATIONLIST_MODAL_DELETE_CLOSE',
  'APPLICATIONLIST_MODAL_DELETING',
  'APPLICATIONLIST_MODAL_DELETION_OK',
  'APPLICATIONLIST_MODAL_DELETION_ERROR',
  'APPLICATIONLIST_ENABLING_OR_DISABLING',
  'APPLICATIONLIST_ENABLE_OR_DISABLE',
  'APPLICATIONLIST_MODAL_ADD_OPEN',
  'APPLICATIONLIST_MODAL_ADD_CLOSE',
  'CREATE_APPLICATION_RESPONSE',
  'CREATE_APPLICATION_TEXT'
]);
