import createActionType from '../../utils/createActionTypes';

export default createActionType([
  'CAMPAIGNLIST_REQUEST',
  'CAMPAIGNLIST_RESPONSE',
  'CAMPAIGNLIST_ERROR',
  'CAMPAIGNLIST_MODAL_DELETE_OPEN',
  'CAMPAIGNLIST_MODAL_DELETE_CLOSE',
  'CAMPAIGNLIST_MODAL_DELETING',
  'CAMPAIGNLIST_MODAL_DELETION_OK',
  'CAMPAIGNLIST_MODAL_DELETION_ERROR',
  'CAMPAIGNLIST_ENABLING_OR_DISABLING',
  'CAMPAIGNLIST_ENABLE_OR_DISABLE',
]);
